export enum Constants {
  LIST_FILMS = "LIST_FILMS",
  GET_FILM_DETAILS = "GET_FILM_DETAILS",
  SHOW_CHARACTER = "SHOW_CHARACTER",
  ADD_FILMS = "ADD_FILMS",
  LOAD_FILMS = "LOAD_FILMS",
  SELECT_FILM = "SELECT_FILM"
}